### ISSUE TITLE
Does this work for huge audio files and their transcripts?

### ISSUE THREAD

**Issue by ramaneswaran** [feldberlin/timething#18]
Thanks for creating this project. I have a doubt regarding its usage, suppose I have university lectures which are 45 minutes in size and the entire transcript for this lecture. Will this method still work for this case

**Comment by purzelrakete** [comment]
hi @ramaneswaran! this now works when you use align-long, e.g. 

```
timething align-long \
    --audio-file fixtures/audio/keanu.mp3 \
    --transcript-file fixtures/keanu.cleaned.txt \
    --alignments-dir aligned \
    --batch-size 10 \
    --n-workers 5
```

previously it did not work for 45 minute lectures, because of the length restrictions imposed by the underlying transformer model.
