### ISSUE TITLE
Dependency mismatch with `transformers`

### ISSUE THREAD

**Issue by jgcodes2020** [feldberlin/timething#19]
## What
Current `timething`'s requirement for `tokenizers` is incompatible with current `transformers`.

## How to reproduce

1. install the package from pip.
2. Try to run `timething --help`

## Expected
No errors at all.

## Additional context
A basic workaround involves the following:
1. Find `dependency_version_check.py` in `transformers`.
2. Find a line that sets `pkgs_to_check_at_runtime` and remove `tokenizers`. This prevents the version check.
  a. There is probably a better way to fix it.
```py
# pkgs_to_check_at_runtime = "python tqdm regex sacremoses requests packaging filelock numpy tokenizers".split()
pkgs_to_check_at_runtime = "python tqdm regex sacremoses requests packaging filelock numpy".split()
```

**Comment by purzelrakete** [comment]
thanks @jgcodes2020, this is now fixed.
