### ISSUE TITLE
Adding West Frisian wav2vec model

### ISSUE THREAD

**Issue by heeringa0** [feldberlin/timething#21]
Could you add West Frisian using the model at: https://huggingface.co/greenw0lf/wav2vec2-large-xlsr-53-frisian-cv-13 ?

The closest language is Dutch - which is available -, but Frisian is too different, so it would help a lot if Frisian was added.

**Comment by purzelrakete** [comment]
@heeringa0 hey there! happy to add it. can you find the right model though? the link you are pointing to is broken.

**Comment by heeringa0** [comment]
Dear Rany,

Thanks for your message.

You are right that the link is broken. The right link is:
https://huggingface.co/RuudVelo/wav2vec2-large-xlsr-53-frisian

Best,
Wilbert


________________________________
